apiVersion: v1
kind: Namespace
metadata:
  name: awp-system
  labels:
    app.kubernetes.io/part-of: ai-workload-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: awp-workloads
  labels:
    app.kubernetes.io/managed-by: ai-workload-platform
